#!/usr/bin/env sh
set -eu

echo "[+] Initialising articles..."
mkdir -p articles
cat <<'EOF' >articles/article1.md
# My first article
###### 1 Jan 1970
Lorem ipsum.
EOF

mkdir -p html

echo "[+] Initialising pages..."
mkdir -p pages
cat <<'EOF' >pages/index.md
# Hello, world!
Welcome to my website.
EOF

mkdir -p resources/images
touch resources/styles.css

echo "[+] Initialising template..."
cat <<'EOF' >template.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/styles.css">
</head>
<body>
$article$
</body>
</html>
EOF

cat <<'EOF'
Done. Edit files inside articles/, pages/, and resources/, then run:

    bobo-run
EOF
