#!/usr/bin/awk -f
# Gets a markdown file, converts it to HTML using smu, slots it into
# template.html and writes the result to html/. Prints a markdown index
# link to stdout.

BEGIN {
	PUBLIC   = "html"
	CMD      = "smu " ARGV[1]
	output   = ARGV[1]
	title    = ""
	date     = ""
	content  = ""

	# Derive output path: replace leading directory with PUBLIC/
	gsub(/^([^\/]*\/)*/, PUBLIC "/", output)
	gsub(/\.md$/, ".html", output)

	while ((CMD | getline line) > 0) {
		content = content line "\n"

		if (title == "" && line ~ /<h1>/) {
			tmp = line
			gsub(/<[^>]*>/, "", tmp)
			title = tmp
		}

		if (date == "" && line ~ /<h6>/) {
			tmp = line
			gsub(/<[^>]*>/, "", tmp)
			date = tmp
		}
	}
	close(CMD)

	ARGV[1] = "template.html"
}

{
	line = $0
	gsub(/\$article\$/, content, line)
	print line > output
}

END {
	link = output
	gsub(/^[^\/]*\//, "", link)
	if (title != "")
		printf "* [%s (%s)](%s)\n", title, date, link
}
