#!/usr/bin/env sh

set -eu

PORT="8080"

cd html 
case "$#" in
0)
	echo [+] Listening on port "$PORT"...
	busybox httpd -f -p "$PORT"
	;;
1)
	busybox httpd -f -p 8080 &
	echo [+] Listening on port "$PORT"
	;;
esac
